version: "3.9"

services:
  db:
    image: mongo
    hostname: audition_mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: audition_db
      MONGO_INITDB_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017
  db_dashboard:
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_DASHBOARD_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_DASHBOARD_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://audition_mongo:27017
